// Vuejs/08_learn_vuerouter/src/pages/About.vue
<!--
 * @Descripttion: 
 * @version: 
 * @Author: by_mori
 * @Date: 2021-10-15 11:34:17
 * @LastEditors: by_mori
 * @LastEditTime: 2021-10-15 11:47:08
-->
<template>
  <div>
    <h2>About</h2>
    <ul>
      <li>About的内容1</li>
      <li>About的内容2</li>
      <li>About的内容3</li>
    </ul>
  </div>
</template>

<script>
export default {

}
</script>

<style scoped>
</style>

// React/React_Basics/15_learn-next/pages/about.js
/*
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2021-12-27 12:08:39
 * @LastEditors: by_mori
 * @LastEditTime: 2021-12-27 13:20:17
 */
import React, { memo } from 'react';

// import AppLayout from '../components/app-layout';

export default memo(function About() {
  return (
    <div>
      <h1>About</h1>
    </div>
  );
});
