// Vuejs/03_learn_component/src/09_具名插槽的使用/NavBar.vue
<!--
 * @Descripttion: 
 * @version: 
 * @Author: by_mori
 * @Date: 2021-10-12 15:55:40
 * @LastEditors: by_mori
 * @LastEditTime: 2021-10-12 16:21:10
-->
<template>
  <div class="nav-bar">
    <div class="left">
      <slot name="left"></slot>
    </div>
    <div class="center">
      <slot name="center"></slot>
    </div>
    <div class="right">
      <slot name="right"></slot>
    </div>

    <!-- 动态插槽名 -->
    <div class="addition">
      <slot :name="name"></slot>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    name: String
  }
  //   data () {
  //     return {
  //       name: 'ioinn'
  //     }
  //   },
}
</script>

<style scoped>
.nav-bar {
  display: flex;
}
.left,
.right,
.center {
  height: 44px;
}
.left,
.right,
addition {
  width: 80px;
  background-color: red;
}
.center {
  flex: 1;
  background-color: blue;
}
</style>

// React/React_Basics/04_learn_component/src/05_React实现slot/NavBar.js
/*
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2021-11-29 13:49:13
 * @LastEditors: by_mori
 * @LastEditTime: 2021-11-29 14:01:59
 */
import React, { Component } from 'react';

export default class NavBar extends Component {
  render() {
    // console.log(this.props.children);

    return (
      <div className="nav-item nav-bar">
        <div className="nav-item nav-left">{this.props.children[0]}</div>
        <div className="nav-item nav-center">{this.props.children[1]}</div>
        <div className="nav-item nav-right">{this.props.children[2]}</div>
      </div>
    );
  }
}
