// React/React_Basics/13_learn-router/src/pages/home.js
/*
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2021-12-10 15:32:46
 * @LastEditors: by_mori
 * @LastEditTime: 2021-12-10 15:33:07
 */
import React, { PureComponent } from 'react';

export default class Home extends PureComponent {
  render() {
    return (
      <div>
        <h2>Home</h2>
      </div>
    );
  }
}

// Vuejs/03_learn_component/src/06_Provide和Inject使用/Home.vue
<!--
 * @Descripttion: 
 * @version: 
 * @Author: by_mori
 * @Date: 2021-10-11 23:33:37
 * @LastEditors: by_mori
 * @LastEditTime: 2021-10-11 23:38:51
-->
<template>
  <div>
    home
    <home-content />
  </div>
</template>

<script>
import HomeContent from './HomeContent.vue'
export default {
  components: { HomeContent },

}
</script>

<style scoped>
</style>
