// Vuejs/04_learn_animation/src/01_动画的基本使用/pages/About.vue
<!--
 * @Descripttion: 
 * @version: 
 * @Author: by_mori
 * @Date: 2021-10-13 01:10:04
 * @LastEditors: by_mori
 * @LastEditTime: 2021-10-13 01:14:20
-->
<template>
  <div>
    <h2>About组件</h2>
    <p>哈哈哈哈</p>
  </div>
</template>

<script>
export default {
  name: 'about'
}
</script>

<style scoped>
</style>

// React/React_Basics/13_learn-router/src/pages/about.js
/*
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2021-12-10 15:32:46
 * @LastEditors: by_mori
 * @LastEditTime: 2021-12-10 15:32:46
 */
import React, { PureComponent } from 'react';

export default class About extends PureComponent {
  render() {
    return (
      <div>
        <h2>About</h2>
      </div>
    );
  }
}
