// Vuejs/03_learn_component/src/11_动态组件的使用/pages/About.vue
<!--
 * @Descripttion: 
 * @version: 
 * @Author: by_mori
 * @Date: 2021-10-12 17:54:16
 * @LastEditors: by_mori
 * @LastEditTime: 2021-10-12 19:48:29
-->
<template>
  <div>
    About
    <button @click="counter++">{{counter}}</button>
  </div>
</template>

<script>
export default {
  name:'about',
  data () {
    return {
      counter: 0
    }
  },
}
</script>

<style scoped>
</style>

// React/React_Basics/13_learn-router/src/pages/about.js
/*
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2021-12-10 15:32:46
 * @LastEditors: by_mori
 * @LastEditTime: 2021-12-10 15:32:46
 */
import React, { PureComponent } from 'react';

export default class About extends PureComponent {
  render() {
    return (
      <div>
        <h2>About</h2>
      </div>
    );
  }
}
