// Vuejs/08_learn_vuerouter/src/pages/Home.vue
<!--
 * @Descripttion: 
 * @version: 
 * @Author: by_mori
 * @Date: 2021-10-15 11:34:03
 * @LastEditors: by_mori
 * @LastEditTime: 2021-10-15 11:47:15
-->
<template>
  <div>
    <h2>Home</h2>
    <ul>
        <li>Home的内容1</li>
        <li>Home的内容2</li>
        <li>Home的内容3</li>
    </ul>
  </div>
</template>

<script>
export default {

}
</script>

<style scoped>
</style>

// React/React_Basics/13_learn-router/src/pages/home.js
/*
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2021-12-10 15:32:46
 * @LastEditors: by_mori
 * @LastEditTime: 2021-12-10 15:33:07
 */
import React, { PureComponent } from 'react';

export default class Home extends PureComponent {
  render() {
    return (
      <div>
        <h2>Home</h2>
      </div>
    );
  }
}
