// Vuejs/23_vue_3.2_pinia_admin/src/views/login/index.vue
<!--
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2022-01-29 17:08:37
 * @LastEditors: by_mori
 * @LastEditTime: 2022-01-29 17:08:37
-->
<template>
    <div>a</div>
</template>
<script lang="ts">
import { ref } from "vue";
const app = {
    name: "App",
    setup() {

    }
}
export default app;
</script>
<style>
#app {
    font-family: Avenir, Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-align: center;
    color: #2c3e50;
    margin-top: 60px;
}
</style>

// React/React_Basics/13_learn-router/src/pages/login.js
/*
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2021-12-10 20:12:44
 * @LastEditors: by_mori
 * @LastEditTime: 2021-12-10 20:12:44
 */
import React, { PureComponent } from 'react';

export default class Login extends PureComponent {
  render() {
    return (
      <div>
        <h2>Login</h2>
      </div>
    );
  }
}
