// Vuejs/08_learn_vuerouter/src/pages/Login.vue
<!--
 * @Descripttion: 
 * @version: 
 * @Author: by_mori
 * @Date: 2021-10-15 17:00:22
 * @LastEditors: by_mori
 * @LastEditTime: 2021-10-15 17:04:50
-->
<template>
  <div>
    <button @click="loginClick">登录</button>
  </div>
</template>

<script>
import { useRouter } from 'vue-router';

export default {
  setup () {
    const router = useRouter();

    const loginClick = () => {

      window.localStorage.setItem("token", "ioinn")

      router.push({
        path: "/home"
      })
    }

    return {
      loginClick
    }
  }
}
</script>


<style scoped>
</style>

// React/React_Basics/13_learn-router/src/pages/login.js
/*
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2021-12-10 20:12:44
 * @LastEditors: by_mori
 * @LastEditTime: 2021-12-10 20:12:44
 */
import React, { PureComponent } from 'react';

export default class Login extends PureComponent {
  render() {
    return (
      <div>
        <h2>Login</h2>
      </div>
    );
  }
}
