// Vuejs/23_vue_3.2_pinia_admin/src/App.vue
<!--
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2022-01-29 16:29:57
 * @LastEditors: by_mori
 * @LastEditTime: 2022-01-29 17:19:38
-->


<template>
  <!-- 路由出口 -->
  <!-- 路由匹配到的组件将渲染在这里 -->
  <router-view />
</template>

<script setup lang="ts">
</script>

<style>
</style>

// React/React_Basics/13_learn-router/src/App.js
/*
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2021-12-09 20:42:47
 * @LastEditors: by_mori
 * @LastEditTime: 2021-12-10 11:52:52
 */
import React, { PureComponent } from 'react';

export default class App extends PureComponent {
  render() {
    return <div>aa</div>;
  }
}
