// React/React_Basics/04_learn_component/src/05_React实现slot/NavBar.js
/*
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2021-11-29 13:49:13
 * @LastEditors: by_mori
 * @LastEditTime: 2021-11-29 14:01:59
 */
import React, { Component } from 'react';

export default class NavBar extends Component {
  render() {
    // console.log(this.props.children);

    return (
      <div className="nav-item nav-bar">
        <div className="nav-item nav-left">{this.props.children[0]}</div>
        <div className="nav-item nav-center">{this.props.children[1]}</div>
        <div className="nav-item nav-right">{this.props.children[2]}</div>
      </div>
    );
  }
}

// Vuejs/03_learn_component/src/13_引用元素和组件/NavBar.vue
<!--
 * @Descripttion: 
 * @version: 
 * @Author: by_mori
 * @Date: 2021-10-12 21:02:46
 * @LastEditors: by_mori
 * @LastEditTime: 2021-10-12 21:21:44
-->
<template>
  <div>
    <h2>NavBar</h2>
    <button @click="getParentAndRoot">获取父组件和根组件</button>
  </div>
</template>

<script>
export default {
  data () {
    return {
      msg: '我是navBar中的msg属性'
    }
  },
  methods: {
    sayHello () {
      console.log('hello navbar');
    },
    getParentAndRoot () {
      // 访问父组件实例
      console.log(this.$parent);
      console.log(this.$parent.mm);
      // 调用父组件 btnClick 方法
      this.$parent.btnClick()

      // 访问根组件
      console.log(this.$root);
    }
  },
}
</script>

<style scoped>
</style>
