// Vuejs/05_composition_api/src/05_生命周期钩子/App.vue
<!--
 * @Descripttion: 
 * @version: 
 * @Author: by_mori
 * @Date: 2021-10-13 21:55:39
 * @LastEditors: by_mori
 * @LastEditTime: 2021-10-13 22:01:49
-->
<template>
  <div>
    <button @click="increment">{{counter}}</button>
  </div>
</template>

<script>
import { onMounted, onUnmounted, onUpdated, ref } from 'vue'
export default {
  setup () {
    const counter = ref(0);
    const increment = () => counter.value++

    onMounted(() => {
      console.log('app onMounted1');
    })
    onMounted(() => {
      console.log('app onMounted2');
    })
    onUpdated(() => {
      console.log('app onUpdated');
    })
    onUnmounted(() => {
      console.log('app onUnmounted');
    })
    return {
      counter,
      increment
    }
  }
}
</script>

<style scoped>
</style>

// React/React_Basics/03_hello_react/src/App.js
/*
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2021-11-28 13:06:47
 * @LastEditors: by_mori
 * @LastEditTime: 2021-11-28 13:16:09
 */

// import React from 'react';
// const { Component } = React;
import React, { Component } from 'react';

export default class App extends Component {
  constructor() {
    super();

    this.state = {
      counter: 0,
    };
  }

  render() {
    return (
      <div>
        <h2>当前计数: {this.state.counter}</h2>
        <button>+</button>
        <button>-</button>
      </div>
    );
  }
}
