// Vuejs/03_learn_component/src/Main.vue
<!--
 * @Descripttion: 
 * @version: 
 * @Author: by_mori
 * @Date: 2021-10-11 20:00:35
 * @LastEditors: by_mori
 * @LastEditTime: 2021-10-11 20:17:08
-->
<template>
  <div class="main">
    <main-banner />
    <main-product-list />
  </div>
</template>

<script>
import MainBanner from './MainBanner.vue'
import MainProductList from './MainProductList.vue'

export default {
  components: {
    MainBanner,
    MainProductList
  },
}
</script>

<style scoped>
</style>

// React/React_Basics/03_hello_react/src/index.js
/*
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2021-11-28 13:04:09
 * @LastEditors: by_mori
 * @LastEditTime: 2021-11-28 13:07:04
 */
import React from 'react';
import ReactDOM from 'react-dom';

import App from './App';

ReactDOM.render(<App />, document.getElementById('root'));
