// React/React_Basics/06_learn_antdesign/src/App.js
/*
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2021-12-03 16:54:31
 * @LastEditors: by_mori
 * @LastEditTime: 2021-12-03 16:54:31
 */
import React, { PureComponent } from 'react';

export default class App extends PureComponent {
  render() {
    return <div>a</div>;
  }
}

// Vuejs/03_learn_component/src/App.vue
<!--
 * @Descripttion: 
 * @version: 
 * @Author: by_mori
 * @Date: 2021-10-11 19:50:51
 * @LastEditors: by_mori
 * @LastEditTime: 2021-10-11 20:09:40
-->
<template>
  <div id="app">
    <Header />
    <Main />
    <Footer />
  </div>
</template>

<script>
import Header from './Header'
import Main from './Main.vue'
import Footer from './Footer'
export default {
  components: {
    Header,
    Main,
    Footer,
  },
}
</script>

<style scoped>
</style>
