// React/React_Basics/06_learn_antdesign/src/index.js
/*
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2021-12-03 15:51:58
 * @LastEditors: by_mori
 * @LastEditTime: 2021-12-03 16:54:11
 */
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

ReactDOM.render(<App />, document.getElementById('root'));

// Vuejs/03_learn_component/src/Main.vue
<!--
 * @Descripttion: 
 * @version: 
 * @Author: by_mori
 * @Date: 2021-10-11 20:00:35
 * @LastEditors: by_mori
 * @LastEditTime: 2021-10-11 20:17:08
-->
<template>
  <div class="main">
    <main-banner />
    <main-product-list />
  </div>
</template>

<script>
import MainBanner from './MainBanner.vue'
import MainProductList from './MainProductList.vue'

export default {
  components: {
    MainBanner,
    MainProductList
  },
}
</script>

<style scoped>
</style>
