// React/React_Basics/13_learn-router/src/pages/about.js
/*
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2021-12-10 15:32:46
 * @LastEditors: by_mori
 * @LastEditTime: 2021-12-10 15:32:46
 */
import React, { PureComponent } from 'react';

export default class About extends PureComponent {
  render() {
    return (
      <div>
        <h2>About</h2>
      </div>
    );
  }
}

// Vuejs/08_learn_vuerouter/src/pages/About.vue
<!--
 * @Descripttion: 
 * @version: 
 * @Author: by_mori
 * @Date: 2021-10-15 11:34:17
 * @LastEditors: by_mori
 * @LastEditTime: 2021-10-15 11:47:08
-->
<template>
  <div>
    <h2>About</h2>
    <ul>
      <li>About的内容1</li>
      <li>About的内容2</li>
      <li>About的内容3</li>
    </ul>
  </div>
</template>

<script>
export default {

}
</script>

<style scoped>
</style>
