// React/React_Basics/05_react_style/src/02_普通的css/home/index.js
/*
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2021-12-02 22:29:32
 * @LastEditors: by_mori
 * @LastEditTime: 2021-12-02 22:36:26
 */
import React, { PureComponent } from 'react';

import './style.css';

export default class Home extends PureComponent {
  render() {
    return (
      <div className="home">
        <h2 className="title">我是home的标题</h2>
        <div className="banner">
          <span>轮播图</span>
        </div>
      </div>
    );
  }
}

// Vuejs/08_learn_vuerouter/src/pages/Home.vue
<!--
 * @Descripttion: 
 * @version: 
 * @Author: by_mori
 * @Date: 2021-10-15 11:34:03
 * @LastEditors: by_mori
 * @LastEditTime: 2021-10-15 11:47:15
-->
<template>
  <div>
    <h2>Home</h2>
    <ul>
        <li>Home的内容1</li>
        <li>Home的内容2</li>
        <li>Home的内容3</li>
    </ul>
  </div>
</template>

<script>
export default {

}
</script>

<style scoped>
</style>
