// React/React_Basics/08_learn_transition/src/App.js
/*
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2021-12-05 20:10:56
 * @LastEditors: by_mori
 * @LastEditTime: 2021-12-05 21:03:59
 */
import React, { PureComponent } from 'react';

import CSSTransitionDemo from './transition/CSSTransitionDemo';

export default class App extends PureComponent {
  render() {
    return (
      <div>
        <CSSTransitionDemo />
      </div>
    );
  }
}

// Vuejs/23_vue_3.2_pinia_admin/src/App.vue
<!--
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2022-01-29 16:29:57
 * @LastEditors: by_mori
 * @LastEditTime: 2022-01-29 17:19:38
-->


<template>
  <!-- 路由出口 -->
  <!-- 路由匹配到的组件将渲染在这里 -->
  <router-view />
</template>

<script setup lang="ts">
</script>

<style>
</style>
