// React/React_Basics/06_learn_antdesign/src/App.js
/*
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2021-12-03 16:54:31
 * @LastEditors: by_mori
 * @LastEditTime: 2021-12-03 16:54:31
 */
import React, { PureComponent } from 'react';

export default class App extends PureComponent {
  render() {
    return <div>a</div>;
  }
}

// Vuejs/22_vue_3.2_admin/src/App.vue
<!--
 * @Descripttion: io小栈 —— ioinn.cn
 * @version: 0.0.1
 * @Author: by_mori
 * @Date: 2022-01-26 11:39:21
 * @LastEditors: by_mori
 * @LastEditTime: 2022-01-28 22:08:04
-->
<template>
  <router-view />
</template>

<script setup>

</script>

<style lang="scss">
.el-message-box__status {
  position: absolute !important;
}
</style>
